[package]
name = "derive_more"
version = "0.1.0"
description = "Derives more traits for simple types"
authors = ["Jelte Fennema <github-tech@jeltef.nl>"]
license = "MIT"
repository = "https://github.com/JelteF/derive_more"

[lib]
name = "derive_more"
plugin = true

[dependencies]
