[package]
name = "derive_more"
version = "0.5.0"
description = "Adds #[derive(x)] macros for more traits"
authors = ["Jelte Fennema <github-tech@jeltef.nl>"]
license = "MIT"
repository = "https://github.com/JelteF/derive_more"

[lib]
name = "derive_more"
proc-macro = true

[dependencies]
quote = "0.3"
syn = "0.10.6"
