[package]
name = "derive_more"
version = "0.6.3"
description = "Adds #[derive(x)] macros for more traits"
authors = ["Jelte Fennema <github-tech@jeltef.nl>"]
license = "MIT"
repository = "https://github.com/JelteF/derive_more"
documentation = "https://jeltef.github.io/derive_more/derive_more/"

readme = "README.md"
keywords = ["derive", "Add", "From", "Constructor", "implementaion"]
categories = ["development-tools", "development-tools::procedural-macro-helpers"]

include = [
    "src/**/*.rs",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "CHANGELOG.md",
]

[lib]
name = "derive_more"
proc-macro = true

[dependencies]
quote = "0.3"
syn = "0.11.4"

[badges]
travis-ci = { repository = "JelteF/derive_more" }
appveyor = { repository = "JelteF/derive_more" }
