on: [push]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: target

  doc_test:
    needs: build
    name: Doc tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download build files
        uses: actions/download-artifact@v1
        with:
          name: build
          path: target
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/JelteF/cargo-external-doc --force
      - uses: actions-rs/cargo@v1
        with:
          command: external-doc

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: test
