on: [push]

name: CI

jobs:
  test:
    name: Test ${{matrix.os}} ${{matrix.toolchain}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu, macOS, windows]
    steps:
      - uses: actions/checkout@master
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  test_features_separate:
    name: Test features
    runs-on: ubuntu-latest
    steps:
      - name: Install tomljson
        run: go get github.com/pelletier/go-toml/cmd/tomljson
      - name: Test
        run: ci/test_all_features.sh

  doc_test:
    name: Doc tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install cargo-external-doc
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/JelteF/cargo-external-doc --force
      - name: Build library
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Run cargo-external-doc
        uses: actions-rs/cargo@v1
        with:
          command: external-doc


  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D clippy::all -D warnings

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install minimal nightly with clipy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
