on: [push]

name: CI

jobs:
  doc_test:
    name: Doc tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/JelteF/cargo-external-doc --force
      - uses: actions-rs/cargo@v1
        with:
          command: external-doc

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Clippy & Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D clippy::all

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
